---
apiVersion: v1
kind: Secret
metadata:
  name: quay-integration-9-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-demo-video/quay-integration-9-gitops